# Databricks notebook source
CATALOG_NAME = 'marketing_analytics_project'

LANDING_SCHEMA = '00_landing'
BRONZE_SCHEMA = '01_bronze'
SILVER_SCHEMA = '02_silver'
GOLD_SCHEMA = '03_gold'

LANDING_VOL = 'raw_files'

# COMMAND ----------

spark.sql(f'CREATE CATALOG IF NOT EXISTS {CATALOG_NAME}')

spark.sql(f'CREATE SCHEMA IF NOT EXISTS {CATALOG_NAME}.{LANDING_SCHEMA}')
spark.sql(f'CREATE SCHEMA IF NOT EXISTS {CATALOG_NAME}.{BRONZE_SCHEMA}')
spark.sql(f'CREATE SCHEMA IF NOT EXISTS {CATALOG_NAME}.{SILVER_SCHEMA}')
spark.sql(f'CREATE SCHEMA IF NOT EXISTS {CATALOG_NAME}.{GOLD_SCHEMA}')

spark.sql(f'CREATE VOLUME IF NOT EXISTS {CATALOG_NAME}.{LANDING_SCHEMA}.{LANDING_VOL}')


# COMMAND ----------

# %sql
# DROP CATALOG marketing_analytics_project CASCADE