-- Databricks notebook source
-- DBTITLE 1,Add Table and Column Comments
-- =====================================================
-- ALTER Statements for mv_gold_campaign_daily_performance
-- =====================================================

-- Add table comment
ALTER MATERIALIZED VIEW marketing_analytics_project.`03_gold`.mv_gold_campaign_daily_performance
SET TBLPROPERTIES (
  'comment' = 'Daily aggregated campaign performance metrics including impressions, clicks, spend, revenue and conversions by campaign and channel'
);

-- Add column comments
ALTER MATERIALIZED VIEW marketing_analytics_project.`03_gold`.mv_gold_campaign_daily_performance
ALTER COLUMN date COMMENT 'Date of campaign activity';

ALTER MATERIALIZED VIEW marketing_analytics_project.`03_gold`.mv_gold_campaign_daily_performance
ALTER COLUMN campaign_id COMMENT 'Identifier for the marketing campaign';

ALTER MATERIALIZED VIEW marketing_analytics_project.`03_gold`.mv_gold_campaign_daily_performance
ALTER COLUMN campaign_name COMMENT 'Descriptive name of the marketing campaign';

ALTER MATERIALIZED VIEW marketing_analytics_project.`03_gold`.mv_gold_campaign_daily_performance
ALTER COLUMN channel COMMENT 'Marketing channel (e.g., Google Ads, YouTube, Instagram, etc)';

ALTER MATERIALIZED VIEW marketing_analytics_project.`03_gold`.mv_gold_campaign_daily_performance
ALTER COLUMN impressions COMMENT 'Total number of ad impressions served';

ALTER MATERIALIZED VIEW marketing_analytics_project.`03_gold`.mv_gold_campaign_daily_performance
ALTER COLUMN clicks COMMENT 'Total number of clicks on the campaign ads';

ALTER MATERIALIZED VIEW marketing_analytics_project.`03_gold`.mv_gold_campaign_daily_performance
ALTER COLUMN spend_usd COMMENT 'Total advertising spend in USD';

ALTER MATERIALIZED VIEW marketing_analytics_project.`03_gold`.mv_gold_campaign_daily_performance
ALTER COLUMN revenue_usd COMMENT 'Total revenue generated in USD from campaign-attributed conversions';

ALTER MATERIALIZED VIEW marketing_analytics_project.`03_gold`.mv_gold_campaign_daily_performance
ALTER COLUMN add_to_cart COMMENT 'Number of add-to-cart conversion events';

ALTER MATERIALIZED VIEW marketing_analytics_project.`03_gold`.mv_gold_campaign_daily_performance
ALTER COLUMN wishlist COMMENT 'Number of wishlist conversion events';

ALTER MATERIALIZED VIEW marketing_analytics_project.`03_gold`.mv_gold_campaign_daily_performance
ALTER COLUMN purchase COMMENT 'Number of purchase conversion events';

ALTER MATERIALIZED VIEW marketing_analytics_project.`03_gold`.mv_gold_campaign_daily_performance
ALTER COLUMN total_no_of_conv COMMENT 'Total number of all conversion events (add_to_cart + wishlist + purchase)';


-- =====================================================
-- ALTER Statements for mv_gold_customer_summary
-- =====================================================

-- Add table comment
ALTER MATERIALIZED VIEW marketing_analytics_project.`03_gold`.mv_gold_customer_summary
SET TBLPROPERTIES (
  'comment' = 'Aggregated customer-level summary of revenue, conversions and engagement metrics by region and customer tier'
);

-- Add column comments
ALTER MATERIALIZED VIEW marketing_analytics_project.`03_gold`.mv_gold_customer_summary
ALTER COLUMN customer_id COMMENT 'Unique identifier for the customer';

ALTER MATERIALIZED VIEW marketing_analytics_project.`03_gold`.mv_gold_customer_summary
ALTER COLUMN region COMMENT 'Geographic region of the customer';

ALTER MATERIALIZED VIEW marketing_analytics_project.`03_gold`.mv_gold_customer_summary
ALTER COLUMN customer_tier COMMENT 'Customer tier or segment classification (e.g., Gold, Silver, Bronze)';

ALTER MATERIALIZED VIEW marketing_analytics_project.`03_gold`.mv_gold_customer_summary
ALTER COLUMN revenue_usd COMMENT 'Total revenue generated by the customer in USD';

ALTER MATERIALIZED VIEW marketing_analytics_project.`03_gold`.mv_gold_customer_summary
ALTER COLUMN add_to_cart COMMENT 'Total number of add-to-cart events by the customer';

ALTER MATERIALIZED VIEW marketing_analytics_project.`03_gold`.mv_gold_customer_summary
ALTER COLUMN wishlist COMMENT 'Total number of wishlist events by the customer';

ALTER MATERIALIZED VIEW marketing_analytics_project.`03_gold`.mv_gold_customer_summary
ALTER COLUMN purchase COMMENT 'Total number of purchase events by the customer';

ALTER MATERIALIZED VIEW marketing_analytics_project.`03_gold`.mv_gold_customer_summary
ALTER COLUMN total_no_of_conv COMMENT 'Total number of all conversion events by the customer (add_to_cart + wishlist + purchase)';